In [2]:
import numpy as np

创建数组：一维、二维,——看最左边几个方括号

In [5]:
arr1=np.array([1,2,3])

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])

一般来说，数组内数据类型保持统一，否则强制转换为字符串

In [7]:
np.array([1,2,True,"hello"])

array(['1', '2', 'True', 'hello'], dtype='<U11')

数组属性：ndim—数组维度；shape—各个维度的元素个数；size-数组元素的总个数；dtype-元素的类型和长度

In [8]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [9]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


即第一个维度有两个数组，第二个维度有三个数组

In [10]:
print(arr1.size)
print(arr2.size)

3
6


In [11]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


int -整数，32-比特长度

除了手动输入数组方法，还提供其他一些创造数组方法：zeros方法(创建长度为X，元素都为0的数组) ；ones;**arange(类似python的range)——针对array的range方法**

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

**arange(起始值，结束值，步长)** 同range一样,建立一个元素数组

In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])