In [1]:
import numpy as np

In [19]:
arr1 = np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

In [20]:
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

[[1 3 5]
 [2 4 6]]


In [18]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int32
int32


In [17]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

In [21]:
arr_all_1 = np.zeros(6)
arr_all_1

array([0., 0., 0., 0., 0., 0.])

In [24]:
arr_even = np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])