In [4]:
import numpy as np

In [5]:
arr1=np.array([1,2,3])

In [15]:
arr2=np.array([4,5,6])

链接——np.concatenate([arr1,arr2])——两个数组为一个新数组

In [16]:
arr3=np.concatenate([arr1,arr2])
arr3

array([1, 2, 3, 4, 5, 6])

排序——numpy中的sort（X）函数，sort（）方法

In [8]:
arr4=np.array([2,9,3,1])

In [11]:
arr5=np.sort(arr4)
print(arr5)
arr4.sort()
print(arr4)

[1 2 3 9]
[1 2 3 9]


排序——python内置sorted函数（返回新列表，不改变原列表）、sort方法（什么都不返回，但是改变原列表）

In [13]:
arr4[0]
arr4[-1]
arr4[1:3]

array([2, 3])

索引——第一个值arr1[0];倒数第二个值arr1[-2];获得一个范围的部分数组arr1[1:4]

数组运算—— + - / * ；数组和单个数字之间（线性代数中，向量和标量的运算）

In [17]:
arr1+arr2

array([5, 7, 9])

In [18]:
arr1-arr2

array([-3, -3, -3])

In [19]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [20]:
arr1*arr2

array([ 4, 10, 18])

广播机制

In [21]:
arr1*3

array([3, 6, 9])

聚合操作：通过一组值得到一个值arr4.max(),arr4.min(),arr4.sum(),arr4.mean()

**根据特定条件筛选数组元素**：数组比列表方便：在arr6=np.array([-33,3,65,9,11]),其中大于6的值？

In [22]:
arr6=np.array([-33,3,65,9,11])

In [24]:
arr6[arr6>6]

array([65,  9, 11])

根据广播机制，>6会被运用于每一个元素，——产生ture和false的布尔值数组以代表是否>6——在方括号中放入布尔值（极元素）

**更复杂的逻辑运算**：与-and-&；或-or-|；非-not-~    筛选所有大于6且小于10的数字

In [25]:
arr6[(arr6>6) & (arr6<10) ]

array([9])