In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,3,2,4,9])
arr1

array([1, 3, 2, 4, 9])

In [4]:
arr2 = np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

In [5]:
arr3 = np.zeros(3)
arr3

array([0., 0., 0.])

In [7]:
arr4= np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [12]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

In [13]:
arr1[2]

3

In [14]:
arr1[-3]

3

In [15]:
arr1[1:4]

array([2, 3, 4])

In [16]:
arr1+arr2

array([ 2.,  3.,  4.,  5., 10.])

In [17]:
arr1*5

array([ 5, 10, 15, 20, 45])

In [19]:
arr1.max()

9

In [20]:
arr1.min()

1

In [21]:
arr1.mean()

3.8

In [22]:
arr1.sum()

19

In [24]:
arr1[(arr1<1) | (arr1>3)]

array([4, 9])